Update npm-publish-github-packages.yml

diff --git a/.github/workflows/npm-publish-github-packages.yml b/.github/workflows/npm-publish-github-packages.yml
--- a/.github/workflows/npm-publish-github-packages.yml
+++ b/.github/workflows/npm-publish-github-packages.yml
@@ -1,6 +1,3 @@
-# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
-# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
-
 name: Node.js Package
 
 on:
@@ -19,7 +16,7 @@ jobs:
       - run: npm i
       - run: npm test
 
-  publish-gpr:
+  publish:
     needs: build
     runs-on: ubuntu-latest
     permissions:
@@ -32,6 +29,18 @@ jobs:
           node-version: 20
           registry-url: https://npm.pkg.github.com/
       - run: npm i
-      - run: npm publish
+      - run: |
+          set +e
+          npm publish || ERROR=$?
+          set -e
+          if [ "$ERROR" == "1" ]; then
+            echo "Publishing failed due to existing version conflict."
+            # Optionally create an issue or comment on PR to notify the conflict
+            curl -X POST \
+              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+              -H "Accept: application/vnd.github.v3+json" \
+              https://api.github.com/repos/${{ github.repository }}/issues \
+              -d '{"title": "Publish Conflict", "body": "Attempted to publish over an existing version. Please bump the version number."}'
+          fi
         env:
-          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
+          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
